name: Java CI/CD with Maven and Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Step 1: Create the .jar artifact (skipping tests to avoid the database error)
      - name: Build with Maven Wrapper
        run: ./mvnw -B package -DskipTests

      # Step 2: Log in to your Docker Hub account
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build the image and push it
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Replace 'your-username' with your actual Docker Hub username
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic:${{ github.run_number }}
      
      - name: Setup Kubeconform
        uses: bmuschko/setup-kubeconform@v1

      - name: Validate Kubernetes Manifests
        # -summary: Shows a clean report
        # -strict: Catches small typos (very helpful!)
        run: kubeconform -summary -strict k8s/

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_DATA }}

      - name: Deploy to Minikube
        run: |
          # 1. Point to the Minikube IP (from your cluster-info)
          # This tells the runner to ignore the 'localhost' in the config 
          # and talk to your actual laptop IP.
          kubectl config set-cluster minikube --server=https://192.168.49.2:8443
          
          # 2. Deploy using the 'insecure' flag to bypass the missing local .crt files
          kubectl apply -f k8s/db.yml --insecure-skip-tls-verify --validate=false
          kubectl apply -f k8s/petclinic.yml --insecure-skip-tls-verify --validate=false
          
          # 3. Refresh the app
          kubectl rollout restart deployment/petclinic --insecure-skip-tls-verify